name: 'course_advanced_dbt'
version: '1.0.0'
config-version: 2

profile: 'course_advanced_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

log-path: 'logs'
target-path: 'target'
packages-install-path: 'dbt_packages'

clean-targets:
  - "target"
  - "dbt_packages"

models:
  course_advanced_dbt:
    +grants:
      select: ['transformer', 'reporter']
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
      +docs:
        node_color: 'orange'
  dbt_project_evaluator:
    +docs:
      show: false

seeds:
  dbt_project_evaluator:
    dbt_project_evaluator_exceptions:
      +enabled: false

on-run-end: ["{{ dbt_project_evaluator.print_dbt_project_evaluator_issues() }}"]
